### ISSUE TITLE
В базе данных указана не та сумма

### ISSUE THREAD

**Issue by HolzQA** [HolzQA/Coursework#4]
Окружение:
ОС Windows 10 Pro
Браузер Google Chrome Версия 118
Java 11

Шаги:

1. Открыть сайт для покупки путешествия (http://localhost:8080/).
2. Нажать кнопку "Купить".
3. Ввести валидные данные во все поля.
4. Нажать кнопку "Продолжить".
5. Открыть SQL console и ввести запрос "SELECT amount FROM payment_entity LIMIT 1".

Фактический результат:
Отобразилось число 4 500 000.

Ожидаемый результат:
Отобразилось число 45 000.

![Bug_in_Database_about_amount](https://github.com/HolzQA/Coursework/assets/117539570/3c5eea7b-cb64-425a-8bd6-ec8679276984)

**Comment by ArRomanov** [comment]
В базе данных сумма хранится в копейках для избежания ошибок при расчетах. Поэтому, сумма из БД, поделенная на 100 будет соответствовать тому, что указано в интерфейсе
